from trading.name_resolution_patch import install_name_resolution_patch
from dashboard.trading_desk_app import run
from dashboard.kis_realtime_panel import render_kis_realtime_panel

install_name_resolution_patch()
run()
render_kis_realtime_panel()
